### ISSUE TITLE
readme_update_basic

### ISSUE THREAD

**Issue by Capitalsav** [polyakovigor/clone-slack#7]
- [x] Add contributor guide for project in Readme.
- [x] Add Authors in Readme.
- [x] Add Setup and runing project guide in Readme.
- [x] Add general project ruls to Readme.

**Comment by polyakovigor** [comment]
1. The test coverage is MANDATORY and it should be at a level not lower than 85%
2. The project, at the moment, is developed on **rails 5.1.6** and **ruby 2.4.1**
   - to indicate the version of ruby we use the file `.ruby-version` - inside type _ruby-2.4.1_
   - to denote gemset we use the file `.ruby-gemset` - inside the _name_of_the_gemset_
3. The development is carried out on the **development** branch. Create working branches from this branch.
    3.1 Go to branch **development** - `git checkout development`
    3.2 Pulling changes - `git pull origin development`
    3.3 Create new branch - `git checkout -b issue_name`
    3.4 `git add`,  `git commit`  & `git push origin branch_name`
    3.5 Create **pull request** with a link to the issue
